services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    networks:
      - backend
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
    networks:
      - backend
    command: sh /app/start.sh
    volumes:
      - .:/app
    restart: always

networks:
  backend:
    driver: bridge
